### ISSUE TITLE
DL# field input issues in Safari browser 

### ISSUE THREAD

**Issue by shevchulya** [aavtamon/boating#36]
1. DL# field is not letting you to input more than one character. 
2. Characters can't be erased after initial input. 
3. Software allows SPACE input as a valid input.
4. In some cases it allows to proceed without putting anything into DL field.

**Comment by aavtamon** [comment]
The original bug is caused by the incorrect handling of the user-select css property by Safari.
This problem is resolved. Please retest.

Another problem reported in this issue is SPACE character allowed as an input. Please create a separate ticket that will request a better validation of the allowed DL. We will need to find out what are the allowed characters across all the states to decide the best validation formula. I was initially going to only allow numbers, but I am not sure if it is a fair assumption that any DL is numeric.

**Comment by aavtamon** [comment]
Actually, I do haver an issue #34 opened for that exact thing, so no need to create a new one.
